services:
  api:
    build:
      context: .
      target: development
    container_name: event-management
    ports:
      - "${PORT}:9000"     
    env_file:
      - .dev.env           
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .dev.env             
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: