name: Run tests (Integratio and Unit tests)

on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Ensure Docker is running
        run: docker info  

      - name: Enable Testcontainers reuse
        run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test    
